// Auto-generated by a2r transpiler

use crate::test::{assert_eq};
use src::core::protocol::{Action, make_action};
pub fn is_valid_kind(kind: &str) -> i64 {
    let k: String = kind.to_string();
    if k == "launch" {
        return 1;
    }
    if k == "open" {
        return 1;
    }
    if k == "capture" {
        return 1;
    }
    if k == "ask" {
        return 1;
    }
    if k == "task" {
        return 1;
    }
    return 0;
}

pub fn action_allowed(mut a: Action, confirmed: i64) -> i64 {
    if is_valid_kind(a.kind) == 0 {
        return 0;
    }
    if a.requires_confirmation == 1 {
        if confirmed != 1 {
            return 0;
        }    }
    return 1;
}

pub fn route(a: Action) -> String {
    if is_valid_kind(a.kind) == 0 {
        return "reject".to_string();
    }
    return a.kind;
}

pub fn actions_for(provider_id: &str, result_id: &str, is_link: i64) -> Vec<serde_json::Value> {
    let rid: String = result_id.to_string();
    let mut out = Vec::new();
    out.push(Action { action_id: "launch".to_string(), label: "Launch".to_string(), kind: "launch".to_string(), target_ref: rid, requires_confirmation: 0 });
    if is_link == 1 {
        out.push(Action { action_id: "open".to_string(), label: "Open".to_string(), kind: "open".to_string(), target_ref: rid, requires_confirmation: 0 });
    }
    return out;
}

fn t_kinds_and_route() {
    assert_eq!(is_valid_kind("launch"), 1);
    assert_eq!(is_valid_kind("open"), 1);
    assert_eq!(is_valid_kind("capture"), 1);
    assert_eq!(is_valid_kind("ask"), 1);
    assert_eq!(is_valid_kind("task"), 1);
    assert_eq!(is_valid_kind("shell"), 0);

    let a = make_action("launch", "Launch", "launch", "calc", 0);
    if route(a.clone()) == "launch" {
        assert_eq!(1, 1);
    } else {
        assert_eq!(1, 0);
    }

    assert_eq!(action_allowed(a.clone(), 0), 1);

    let evil = make_action("x", "x", "shell", "evil", 0);
    if route(evil.clone()) == "reject" {
        assert_eq!(1, 1);
    } else {
        assert_eq!(1, 0);
    }

    assert_eq!(action_allowed(evil.clone(), 1), 0);

    let confirm = make_action("task", "Migrate", "task", "m1", 1);
    assert_eq!(action_allowed(confirm.clone(), 0), 0);
    assert_eq!(action_allowed(confirm.clone(), 1), 1);
}

fn t_actions_for_links() {
    let a = actions_for("apps", "calc", 0);
    assert_eq!((a.len() as i64), 1);
    let b = actions_for("quicklinks", "gh", 1);
    assert_eq!((b.len() as i64), 2);
    if b[(1) as usize].clone().kind.to_string() == "open" {
        assert_eq!(1, 1);
    } else {
        assert_eq!(1, 0);
    }

}
